language: php

cache: 
    composer: true
matrix:
    include:
        #- php: 5.4
        #- php: 5.5
        - php: 5.6
        #- php: 7
        #- php: hhvm
    fast_finish: true
before_script: 
  - phpenv config-rm xdebug.ini
  - if [ "$deps" == "low" ]; then composer update --prefer-source --prefer-lowest --prefer-stable; fi
  - if [ "$deps" != "low" ]; then composer install --prefer-source; fi

script: composer test
